# Generated by Django 4.2.7 on 2023-11-25 08:36

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_order_order_status_alter_order_creation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='creation',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='creation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='creation',
        ),
        migrations.AddField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 25, 8, 36, 8, 484480, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 25, 8, 36, 29, 958748)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
